services:
  - type: web
    name: leave-system-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: JWT_SECRET
        sync: false
      - key: DB_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
